export const PRODUCT_FIELD_OPTIONS = {
	productType: [
		"Latex Balloons",
		"Foil Balloons",
		"Bubble Balloons",
		"Modeling Balloons",
	],
	occasion: [
		"Birthday",
		"Wedding",
		"Baby Shower",
		"Anniversary",
		"Graduation",
		"Holiday",
	],
	color: [
		"Red",
		"Blue",
		"Pink",
		"Gold",
		"Silver",
		"Green",
		"Purple",
		"Orange",
		"Black",
		"White",
	],
	manufacturer: ["Qualatex", "Anagram", "Betallic", "CTI", "Convergram"],
	size: ['9"', '11"', '16"', '18"', '36"', '40"'],
	texture: ["Matte", "Pearl", "Chrome", "Metallic", "Transparent"],
} as const;

export type FieldOptions = typeof PRODUCT_FIELD_OPTIONS;
export type Field = keyof FieldOptions;
export type FieldFilters = {
	[K in Field]: FieldOptions[K][number][];
};

export type Product = {
	id: string;
	name: string;
	productType: string;
	occasion: string;
	color: string;
	manufacturer: string;
	size: string;
	texture: string;
	quantity: number;
	imageUrl?: string;
};

export const BALLOON_PRODUCTS: Product[] = [
	{
		id: "8901234567890",
		name: "Red Heart Birthday Balloon",
		productType: "Latex Balloons",
		occasion: "Birthday",
		color: "Red",
		manufacturer: "Qualatex",
		size: '11"',
		texture: "Matte",
		quantity: 18,
	},
	{
		id: "8901234567891",
		name: "Gold Wedding Foil Number",
		productType: "Foil Balloons",
		occasion: "Wedding",
		color: "Gold",
		manufacturer: "Anagram",
		size: '40"',
		texture: "Metallic",
		quantity: 71,
	},
	{
		id: "8901234567892",
		name: "Pink Baby Shower Elephant",
		productType: "Foil Balloons",
		occasion: "Baby Shower",
		color: "Pink",
		manufacturer: "Betallic",
		size: '36"',
		texture: "Pearl",
		quantity: 82,
	},
	{
		id: "8901234567893",
		name: "Blue Graduation Cap",
		productType: "Foil Balloons",
		occasion: "Graduation",
		color: "Blue",
		manufacturer: "CTI",
		size: '18"',
		texture: "Matte",
		quantity: 26,
	},
	{
		id: "8901234567894",
		name: "Silver Anniversary Stars",
		productType: "Latex Balloons",
		occasion: "Anniversary",
		color: "Silver",
		manufacturer: "Qualatex",
		size: '16"',
		texture: "Chrome",
		quantity: 33,
	},
	{
		id: "8901234500006",
		name: "Christmas Tree Holiday Balloon",
		productType: "Foil Balloons",
		occasion: "Holiday",
		color: "Green",
		manufacturer: "Convergram",
		size: '18"',
		texture: "Metallic",
		quantity: 54,
	},
	{
		id: "8901234500007",
		name: "Purple Modeling Balloon Pack",
		productType: "Modeling Balloons",
		occasion: "Birthday",
		color: "Purple",
		manufacturer: "Qualatex",
		size: '9"',
		texture: "Matte",
		quantity: 34,
	},
	{
		id: "8901234500008",
		name: "Clear Bubble Wedding Balloon",
		productType: "Bubble Balloons",
		occasion: "Wedding",
		color: "White",
		manufacturer: "Betallic",
		size: '18"',
		texture: "Transparent",
		quantity: 11,
	},
	{
		id: "8901234500009",
		name: "Orange Halloween Pumpkin",
		productType: "Foil Balloons",
		occasion: "Holiday",
		color: "Orange",
		manufacturer: "Anagram",
		size: '16"',
		texture: "Matte",
		quantity: 66,
	},
	{
		id: "8901234500010",
		name: "Black Graduation 2024",
		productType: "Latex Balloons",
		occasion: "Graduation",
		color: "Black",
		manufacturer: "CTI",
		size: '11"',
		texture: "Pearl",
		quantity: 68,
	},
	{
		id: "8901234500011",
		name: "Rose Gold Baby Girl",
		productType: "Foil Balloons",
		occasion: "Baby Shower",
		color: "Pink",
		manufacturer: "Convergram",
		size: '36"',
		texture: "Chrome",
		quantity: 100,
	},
	{
		id: "8901234500012",
		name: "Red Valentine Heart",
		productType: "Latex Balloons",
		occasion: "Anniversary",
		color: "Red",
		manufacturer: "Qualatex",
		size: '16"',
		texture: "Pearl",
		quantity: 40,
	},
	{
		id: "8901234500013",
		name: "Blue Modeling Animal Kit",
		productType: "Modeling Balloons",
		occasion: "Birthday",
		color: "Blue",
		manufacturer: "Betallic",
		size: '9"',
		texture: "Matte",
		quantity: 90,
	},
	{
		id: "8901234500014",
		name: "Gold 50th Anniversary",
		productType: "Foil Balloons",
		occasion: "Anniversary",
		color: "Gold",
		manufacturer: "Anagram",
		size: '18"',
		texture: "Metallic",
		quantity: 59,
	},
	{
		id: "8901234500015",
		name: "Pink Princess Birthday",
		productType: "Latex Balloons",
		occasion: "Birthday",
		color: "Pink",
		manufacturer: "CTI",
		size: '11"',
		texture: "Pearl",
		quantity: 40,
	},
	{
		id: "8901234500016",
		name: "Green Christmas Wreath",
		productType: "Foil Balloons",
		occasion: "Holiday",
		color: "Green",
		manufacturer: "Qualatex",
		size: '18"',
		texture: "Matte",
		quantity: 27,
	},
	{
		id: "8901234500017",
		name: "White Wedding Doves",
		productType: "Latex Balloons",
		occasion: "Wedding",
		color: "White",
		manufacturer: "Betallic",
		size: '16"',
		texture: "Pearl",
		quantity: 33,
	},
	{
		id: "8901234500018",
		name: "Purple Graduation 2025",
		productType: "Foil Balloons",
		occasion: "Graduation",
		color: "Purple",
		manufacturer: "Convergram",
		size: '40"',
		texture: "Chrome",
		quantity: 50,
	},
	{
		id: "8901234500019",
		name: "Orange Tiger Modeling",
		productType: "Modeling Balloons",
		occasion: "Birthday",
		color: "Orange",
		manufacturer: "Anagram",
		size: '9"',
		texture: "Matte",
		quantity: 88,
	},
	{
		id: "8901234500020",
		name: "Silver New Year 2025",
		productType: "Latex Balloons",
		occasion: "Holiday",
		color: "Silver",
		manufacturer: "CTI",
		size: '11"',
		texture: "Chrome",
		quantity: 18,
	},
	{
		id: "8901234500021",
		name: "Blue Baby Boy Footprints",
		productType: "Foil Balloons",
		occasion: "Baby Shower",
		color: "Blue",
		manufacturer: "Qualatex",
		size: '18"',
		texture: "Metallic",
		quantity: 80,
	},
	{
		id: "8901234500022",
		name: "Red Fire Truck Birthday",
		productType: "Latex Balloons",
		occasion: "Birthday",
		color: "Red",
		manufacturer: "Betallic",
		size: '16"',
		texture: "Matte",
		quantity: 53,
	},
	{
		id: "8901234500023",
		name: "Gold Wedding Rings",
		productType: "Foil Balloons",
		occasion: "Wedding",
		color: "Gold",
		manufacturer: "Convergram",
		size: '36"',
		texture: "Chrome",
		quantity: 82,
	},
	{
		id: "8901234500024",
		name: "Green Dinosaur Modeling",
		productType: "Modeling Balloons",
		occasion: "Birthday",
		color: "Green",
		manufacturer: "Anagram",
		size: '9"',
		texture: "Matte",
		quantity: 69,
	},
	{
		id: "8901234500025",
		name: "Pink Unicorn Bubble",
		productType: "Bubble Balloons",
		occasion: "Birthday",
		color: "Pink",
		manufacturer: "CTI",
		size: '18"',
		texture: "Transparent",
		quantity: 20,
	},
	{
		id: "8901234500026",
		name: "Black Halloween Bat",
		productType: "Foil Balloons",
		occasion: "Holiday",
		color: "Black",
		manufacturer: "Qualatex",
		size: '16"',
		texture: "Matte",
		quantity: 72,
	},
	{
		id: "8901234500027",
		name: "White Dove Wedding",
		productType: "Latex Balloons",
		occasion: "Wedding",
		color: "White",
		manufacturer: "Betallic",
		size: '11"',
		texture: "Pearl",
		quantity: 64,
	},
	{
		id: "8901234500028",
		name: "Purple Congrats Grad",
		productType: "Latex Balloons",
		occasion: "Graduation",
		color: "Purple",
		manufacturer: "Convergram",
		size: '16"',
		texture: "Chrome",
		quantity: 56,
	},
	{
		id: "8901234500029",
		name: "Orange Pumpkin Halloween",
		productType: "Latex Balloons",
		occasion: "Holiday",
		color: "Orange",
		manufacturer: "Anagram",
		size: '11"',
		texture: "Matte",
		quantity: 71,
	},
	{
		id: "8901234500030",
		name: "Silver 25th Anniversary",
		productType: "Foil Balloons",
		occasion: "Anniversary",
		color: "Silver",
		manufacturer: "CTI",
		size: '18"',
		texture: "Metallic",
		quantity: 52,
	},
	{
		id: "8901234500031",
		name: "Blue Shark Modeling",
		productType: "Modeling Balloons",
		occasion: "Birthday",
		color: "Blue",
		manufacturer: "Qualatex",
		size: '9"',
		texture: "Matte",
		quantity: 59,
	},
	{
		id: "8901234500032",
		name: "Pink Baby Girl Bottle",
		productType: "Foil Balloons",
		occasion: "Baby Shower",
		color: "Pink",
		manufacturer: "Betallic",
		size: '36"',
		texture: "Pearl",
		quantity: 8,
	},
	{
		id: "8901234500033",
		name: "Red Christmas Santa",
		productType: "Latex Balloons",
		occasion: "Holiday",
		color: "Red",
		manufacturer: "Convergram",
		size: '16"',
		texture: "Matte",
		quantity: 64,
	},
	{
		id: "8901234500034",
		name: "Gold Star Graduation",
		productType: "Foil Balloons",
		occasion: "Graduation",
		color: "Gold",
		manufacturer: "Anagram",
		size: '40"',
		texture: "Chrome",
		quantity: 10,
	},
	{
		id: "8901234500035",
		name: "Green Lucky Shamrock",
		productType: "Latex Balloons",
		occasion: "Holiday",
		color: "Green",
		manufacturer: "CTI",
		size: '11"',
		texture: "Pearl",
		quantity: 35,
	},
	{
		id: "8901234500036",
		name: "White Angel Wings",
		productType: "Foil Balloons",
		occasion: "Anniversary",
		color: "White",
		manufacturer: "Qualatex",
		size: '18"',
		texture: "Metallic",
		quantity: 16,
	},
	{
		id: "8901234500037",
		name: "Purple Butterfly Modeling",
		productType: "Modeling Balloons",
		occasion: "Birthday",
		color: "Purple",
		manufacturer: "Betallic",
		size: '9"',
		texture: "Matte",
		quantity: 87,
	},
	{
		id: "8901234500038",
		name: "Orange Basketball Sports",
		productType: "Latex Balloons",
		occasion: "Birthday",
		color: "Orange",
		manufacturer: "Convergram",
		size: '16"',
		texture: "Matte",
		quantity: 82,
	},
	{
		id: "8901234500039",
		name: "Black Elegant Anniversary",
		productType: "Latex Balloons",
		occasion: "Anniversary",
		color: "Black",
		manufacturer: "Anagram",
		size: '11"',
		texture: "Chrome",
		quantity: 9,
	},
	{
		id: "8901234500040",
		name: "Blue Baby Boy Rattle",
		productType: "Foil Balloons",
		occasion: "Baby Shower",
		color: "Blue",
		manufacturer: "CTI",
		size: '18"',
		texture: "Pearl",
		quantity: 19,
	},
	{
		id: "8901234500041",
		name: "Pink Flower Power",
		productType: "Latex Balloons",
		occasion: "Birthday",
		color: "Pink",
		manufacturer: "Qualatex",
		size: '16"',
		texture: "Pearl",
		quantity: 72,
	},
	{
		id: "8901234500042",
		name: "Silver Sparkle Wedding",
		productType: "Bubble Balloons",
		occasion: "Wedding",
		color: "Silver",
		manufacturer: "Betallic",
		size: '18"',
		texture: "Transparent",
		quantity: 35,
	},
	{
		id: "8901234500043",
		name: "Red Apple Teacher",
		productType: "Foil Balloons",
		occasion: "Graduation",
		color: "Red",
		manufacturer: "Convergram",
		size: '18"',
		texture: "Matte",
		quantity: 47,
	},
	{
		id: "8901234500044",
		name: "Green Cactus Modeling",
		productType: "Modeling Balloons",
		occasion: "Birthday",
		color: "Green",
		manufacturer: "Anagram",
		size: '9"',
		texture: "Matte",
		quantity: 68,
	},
	{
		id: "8901234500045",
		name: "Gold Turkey Thanksgiving",
		productType: "Latex Balloons",
		occasion: "Holiday",
		color: "Gold",
		manufacturer: "CTI",
		size: '11"',
		texture: "Metallic",
		quantity: 24,
	},
	{
		id: "8901234500046",
		name: "White Snowflake Winter",
		productType: "Foil Balloons",
		occasion: "Holiday",
		color: "White",
		manufacturer: "Qualatex",
		size: '16"',
		texture: "Chrome",
		quantity: 30,
	},
	{
		id: "8901234500047",
		name: "Purple Dragon Modeling",
		productType: "Modeling Balloons",
		occasion: "Birthday",
		color: "Purple",
		manufacturer: "Betallic",
		size: '9"',
		texture: "Matte",
		quantity: 23,
	},
	{
		id: "8901234500048",
		name: "Blue Ocean Bubble",
		productType: "Bubble Balloons",
		occasion: "Birthday",
		color: "Blue",
		manufacturer: "Convergram",
		size: '18"',
		texture: "Transparent",
		quantity: 11,
	},
	{
		id: "8901234500049",
		name: "Orange Sunset Anniversary",
		productType: "Latex Balloons",
		occasion: "Anniversary",
		color: "Orange",
		manufacturer: "Anagram",
		size: '16"',
		texture: "Pearl",
		quantity: 10,
	},
	{
		id: "8901234500050",
		name: "Black Tuxedo Wedding",
		productType: "Foil Balloons",
		occasion: "Wedding",
		color: "Black",
		manufacturer: "CTI",
		size: '36"',
		texture: "Matte",
		quantity: 41,
	},
];
