export const PRODUCT_FIELD_OPTIONS = {
	productType: [
		"Latex Balloons",
		"Foil Balloons",
		"Bubble Balloons",
		"Modeling Balloons",
	],
	occasion: [
		"Birthday",
		"Wedding",
		"Baby Shower",
		"Anniversary",
		"Graduation",
		"Holiday",
	],
	color: [
		"Red",
		"Blue",
		"Pink",
		"Gold",
		"Silver",
		"Green",
		"Purple",
		"Orange",
		"Black",
		"White",
	],
	manufacturer: ["Qualatex", "Anagram", "Betallic", "CTI", "Convergram"],
	size: ['9"', '11"', '16"', '18"', '36"', '40"'],
	texture: ["Matte", "Pearl", "Chrome", "Metallic", "Transparent"],
} as const;

export type FieldOptions = typeof PRODUCT_FIELD_OPTIONS;
export type Field = keyof FieldOptions;
export type FieldFilters = {
	[K in Field]: FieldOptions[K][number][];
};

export type Product = {
	id: number;
	name: string;
	productType: string;
	occasion: string;
	color: string;
	manufacturer: string;
	size: string;
	texture: string;
	price: number;
	imageUrl?: string;
};

export const BALLOON_PRODUCTS: Product[] = [
	{
		id: 1,
		name: "Red Heart Birthday Balloon",
		productType: "Latex Balloons",
		occasion: "Birthday",
		color: "Red",
		manufacturer: "Qualatex",
		size: '11"',
		texture: "Matte",
		price: 2.99,
	},
	{
		id: 2,
		name: "Gold Wedding Foil Number",
		productType: "Foil Balloons",
		occasion: "Wedding",
		color: "Gold",
		manufacturer: "Anagram",
		size: '40"',
		texture: "Metallic",
		price: 12.99,
	},
	{
		id: 3,
		name: "Pink Baby Shower Elephant",
		productType: "Foil Balloons",
		occasion: "Baby Shower",
		color: "Pink",
		manufacturer: "Betallic",
		size: '36"',
		texture: "Pearl",
		price: 8.99,
	},
	{
		id: 4,
		name: "Blue Graduation Cap",
		productType: "Foil Balloons",
		occasion: "Graduation",
		color: "Blue",
		manufacturer: "CTI",
		size: '18"',
		texture: "Matte",
		price: 6.99,
	},
	{
		id: 5,
		name: "Silver Anniversary Stars",
		productType: "Latex Balloons",
		occasion: "Anniversary",
		color: "Silver",
		manufacturer: "Qualatex",
		size: '16"',
		texture: "Chrome",
		price: 4.99,
	},
	{
		id: 6,
		name: "Christmas Tree Holiday Balloon",
		productType: "Foil Balloons",
		occasion: "Holiday",
		color: "Green",
		manufacturer: "Convergram",
		size: '18"',
		texture: "Metallic",
		price: 7.99,
	},
	{
		id: 7,
		name: "Purple Modeling Balloon Pack",
		productType: "Modeling Balloons",
		occasion: "Birthday",
		color: "Purple",
		manufacturer: "Qualatex",
		size: '9"',
		texture: "Matte",
		price: 3.99,
	},
	{
		id: 8,
		name: "Clear Bubble Wedding Balloon",
		productType: "Bubble Balloons",
		occasion: "Wedding",
		color: "White",
		manufacturer: "Betallic",
		size: '18"',
		texture: "Transparent",
		price: 15.99,
	},
	{
		id: 9,
		name: "Orange Halloween Pumpkin",
		productType: "Foil Balloons",
		occasion: "Holiday",
		color: "Orange",
		manufacturer: "Anagram",
		size: '16"',
		texture: "Matte",
		price: 5.99,
	},
	{
		id: 10,
		name: "Black Graduation 2024",
		productType: "Latex Balloons",
		occasion: "Graduation",
		color: "Black",
		manufacturer: "CTI",
		size: '11"',
		texture: "Pearl",
		price: 3.49,
	},
	{
		id: 11,
		name: "Rose Gold Baby Girl",
		productType: "Foil Balloons",
		occasion: "Baby Shower",
		color: "Pink",
		manufacturer: "Convergram",
		size: '36"',
		texture: "Chrome",
		price: 11.99,
	},
	{
		id: 12,
		name: "Red Valentine Heart",
		productType: "Latex Balloons",
		occasion: "Anniversary",
		color: "Red",
		manufacturer: "Qualatex",
		size: '16"',
		texture: "Pearl",
		price: 4.25,
	},
	{
		id: 13,
		name: "Blue Modeling Animal Kit",
		productType: "Modeling Balloons",
		occasion: "Birthday",
		color: "Blue",
		manufacturer: "Betallic",
		size: '9"',
		texture: "Matte",
		price: 6.99,
	},
	{
		id: 14,
		name: "Gold 50th Anniversary",
		productType: "Foil Balloons",
		occasion: "Anniversary",
		color: "Gold",
		manufacturer: "Anagram",
		size: '18"',
		texture: "Metallic",
		price: 9.99,
	},
	{
		id: 15,
		name: "Pink Princess Birthday",
		productType: "Latex Balloons",
		occasion: "Birthday",
		color: "Pink",
		manufacturer: "CTI",
		size: '11"',
		texture: "Pearl",
		price: 2.75,
	},
	{
		id: 16,
		name: "Green Christmas Wreath",
		productType: "Foil Balloons",
		occasion: "Holiday",
		color: "Green",
		manufacturer: "Qualatex",
		size: '18"',
		texture: "Matte",
		price: 8.25,
	},
	{
		id: 17,
		name: "White Wedding Doves",
		productType: "Latex Balloons",
		occasion: "Wedding",
		color: "White",
		manufacturer: "Betallic",
		size: '16"',
		texture: "Pearl",
		price: 5.5,
	},
	{
		id: 18,
		name: "Purple Graduation 2025",
		productType: "Foil Balloons",
		occasion: "Graduation",
		color: "Purple",
		manufacturer: "Convergram",
		size: '40"',
		texture: "Chrome",
		price: 14.99,
	},
	{
		id: 19,
		name: "Orange Tiger Modeling",
		productType: "Modeling Balloons",
		occasion: "Birthday",
		color: "Orange",
		manufacturer: "Anagram",
		size: '9"',
		texture: "Matte",
		price: 4.5,
	},
	{
		id: 20,
		name: "Silver New Year 2025",
		productType: "Latex Balloons",
		occasion: "Holiday",
		color: "Silver",
		manufacturer: "CTI",
		size: '11"',
		texture: "Chrome",
		price: 3.99,
	},
	{
		id: 21,
		name: "Blue Baby Boy Footprints",
		productType: "Foil Balloons",
		occasion: "Baby Shower",
		color: "Blue",
		manufacturer: "Qualatex",
		size: '18"',
		texture: "Metallic",
		price: 7.75,
	},
	{
		id: 22,
		name: "Red Fire Truck Birthday",
		productType: "Latex Balloons",
		occasion: "Birthday",
		color: "Red",
		manufacturer: "Betallic",
		size: '16"',
		texture: "Matte",
		price: 4.99,
	},
	{
		id: 23,
		name: "Gold Wedding Rings",
		productType: "Foil Balloons",
		occasion: "Wedding",
		color: "Gold",
		manufacturer: "Convergram",
		size: '36"',
		texture: "Chrome",
		price: 13.5,
	},
	{
		id: 24,
		name: "Green Dinosaur Modeling",
		productType: "Modeling Balloons",
		occasion: "Birthday",
		color: "Green",
		manufacturer: "Anagram",
		size: '9"',
		texture: "Matte",
		price: 5.25,
	},
	{
		id: 25,
		name: "Pink Unicorn Bubble",
		productType: "Bubble Balloons",
		occasion: "Birthday",
		color: "Pink",
		manufacturer: "CTI",
		size: '18"',
		texture: "Transparent",
		price: 18.99,
	},
	{
		id: 26,
		name: "Black Halloween Bat",
		productType: "Foil Balloons",
		occasion: "Holiday",
		color: "Black",
		manufacturer: "Qualatex",
		size: '16"',
		texture: "Matte",
		price: 6.5,
	},
	{
		id: 27,
		name: "White Dove Wedding",
		productType: "Latex Balloons",
		occasion: "Wedding",
		color: "White",
		manufacturer: "Betallic",
		size: '11"',
		texture: "Pearl",
		price: 3.75,
	},
	{
		id: 28,
		name: "Purple Congrats Grad",
		productType: "Latex Balloons",
		occasion: "Graduation",
		color: "Purple",
		manufacturer: "Convergram",
		size: '16"',
		texture: "Chrome",
		price: 4.25,
	},
	{
		id: 29,
		name: "Orange Pumpkin Halloween",
		productType: "Latex Balloons",
		occasion: "Holiday",
		color: "Orange",
		manufacturer: "Anagram",
		size: '11"',
		texture: "Matte",
		price: 2.99,
	},
	{
		id: 30,
		name: "Silver 25th Anniversary",
		productType: "Foil Balloons",
		occasion: "Anniversary",
		color: "Silver",
		manufacturer: "CTI",
		size: '18"',
		texture: "Metallic",
		price: 8.99,
	},
	{
		id: 31,
		name: "Blue Shark Modeling",
		productType: "Modeling Balloons",
		occasion: "Birthday",
		color: "Blue",
		manufacturer: "Qualatex",
		size: '9"',
		texture: "Matte",
		price: 4.75,
	},
	{
		id: 32,
		name: "Pink Baby Girl Bottle",
		productType: "Foil Balloons",
		occasion: "Baby Shower",
		color: "Pink",
		manufacturer: "Betallic",
		size: '36"',
		texture: "Pearl",
		price: 10.5,
	},
	{
		id: 33,
		name: "Red Christmas Santa",
		productType: "Latex Balloons",
		occasion: "Holiday",
		color: "Red",
		manufacturer: "Convergram",
		size: '16"',
		texture: "Matte",
		price: 5.99,
	},
	{
		id: 34,
		name: "Gold Star Graduation",
		productType: "Foil Balloons",
		occasion: "Graduation",
		color: "Gold",
		manufacturer: "Anagram",
		size: '40"',
		texture: "Chrome",
		price: 16.99,
	},
	{
		id: 35,
		name: "Green Lucky Shamrock",
		productType: "Latex Balloons",
		occasion: "Holiday",
		color: "Green",
		manufacturer: "CTI",
		size: '11"',
		texture: "Pearl",
		price: 3.25,
	},
	{
		id: 36,
		name: "White Angel Wings",
		productType: "Foil Balloons",
		occasion: "Anniversary",
		color: "White",
		manufacturer: "Qualatex",
		size: '18"',
		texture: "Metallic",
		price: 7.5,
	},
	{
		id: 37,
		name: "Purple Butterfly Modeling",
		productType: "Modeling Balloons",
		occasion: "Birthday",
		color: "Purple",
		manufacturer: "Betallic",
		size: '9"',
		texture: "Matte",
		price: 5.5,
	},
	{
		id: 38,
		name: "Orange Basketball Sports",
		productType: "Latex Balloons",
		occasion: "Birthday",
		color: "Orange",
		manufacturer: "Convergram",
		size: '16"',
		texture: "Matte",
		price: 4.5,
	},
	{
		id: 39,
		name: "Black Elegant Anniversary",
		productType: "Latex Balloons",
		occasion: "Anniversary",
		color: "Black",
		manufacturer: "Anagram",
		size: '11"',
		texture: "Chrome",
		price: 3.99,
	},
	{
		id: 40,
		name: "Blue Baby Boy Rattle",
		productType: "Foil Balloons",
		occasion: "Baby Shower",
		color: "Blue",
		manufacturer: "CTI",
		size: '18"',
		texture: "Pearl",
		price: 8.25,
	},
	{
		id: 41,
		name: "Pink Flower Power",
		productType: "Latex Balloons",
		occasion: "Birthday",
		color: "Pink",
		manufacturer: "Qualatex",
		size: '16"',
		texture: "Pearl",
		price: 4.75,
	},
	{
		id: 42,
		name: "Silver Sparkle Wedding",
		productType: "Bubble Balloons",
		occasion: "Wedding",
		color: "Silver",
		manufacturer: "Betallic",
		size: '18"',
		texture: "Transparent",
		price: 22.99,
	},
	{
		id: 43,
		name: "Red Apple Teacher",
		productType: "Foil Balloons",
		occasion: "Graduation",
		color: "Red",
		manufacturer: "Convergram",
		size: '18"',
		texture: "Matte",
		price: 6.99,
	},
	{
		id: 44,
		name: "Green Cactus Modeling",
		productType: "Modeling Balloons",
		occasion: "Birthday",
		color: "Green",
		manufacturer: "Anagram",
		size: '9"',
		texture: "Matte",
		price: 4.99,
	},
	{
		id: 45,
		name: "Gold Turkey Thanksgiving",
		productType: "Latex Balloons",
		occasion: "Holiday",
		color: "Gold",
		manufacturer: "CTI",
		size: '11"',
		texture: "Metallic",
		price: 3.5,
	},
	{
		id: 46,
		name: "White Snowflake Winter",
		productType: "Foil Balloons",
		occasion: "Holiday",
		color: "White",
		manufacturer: "Qualatex",
		size: '16"',
		texture: "Chrome",
		price: 7.25,
	},
	{
		id: 47,
		name: "Purple Dragon Modeling",
		productType: "Modeling Balloons",
		occasion: "Birthday",
		color: "Purple",
		manufacturer: "Betallic",
		size: '9"',
		texture: "Matte",
		price: 6.25,
	},
	{
		id: 48,
		name: "Blue Ocean Bubble",
		productType: "Bubble Balloons",
		occasion: "Birthday",
		color: "Blue",
		manufacturer: "Convergram",
		size: '18"',
		texture: "Transparent",
		price: 19.99,
	},
	{
		id: 49,
		name: "Orange Sunset Anniversary",
		productType: "Latex Balloons",
		occasion: "Anniversary",
		color: "Orange",
		manufacturer: "Anagram",
		size: '16"',
		texture: "Pearl",
		price: 4.99,
	},
	{
		id: 50,
		name: "Black Tuxedo Wedding",
		productType: "Foil Balloons",
		occasion: "Wedding",
		color: "Black",
		manufacturer: "CTI",
		size: '36"',
		texture: "Matte",
		price: 12.75,
	},
];
