import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
	card: {
		backgroundColor: "white",
		borderRadius: 12,
		padding: 16,
		marginVertical: 8,
		elevation: 2,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 1 },
		shadowOpacity: 0.1,
		shadowRadius: 2,
	},
	cardHeader: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "flex-start",
		marginBottom: 12,
	},
	headerLeft: {
		flex: 1,
		marginRight: 12,
	},
	productNameRow: {
		flexDirection: "row",
		alignItems: "center",
		gap: 8,
		flexWrap: "wrap",
	},
	headerRight: {
		flexDirection: "row",
		alignItems: "center",
		gap: 8,
	},
	productName: {
		fontSize: 16,
		fontWeight: "600",
		color: "#1a1a1a",
		marginBottom: 2,
	},
	externalCount: {
		fontSize: 12,
		color: "#6c757d",
		fontStyle: "italic",
	},
	quantity: {
		fontSize: 18,
		fontWeight: "bold",
		color: "#007bff",
	},
	expandButton: {
		padding: 4,
	},
	occasionsContainer: {
		flexDirection: "row",
		flexWrap: "wrap",
		marginTop: 12,
		marginBottom: 4,
		gap: 6,
		justifyContent: "flex-start",
	},
	occasionPill: {
		flexDirection: "row",
		alignItems: "center",
		backgroundColor: "#f8f9fa",
		paddingHorizontal: 8,
		paddingVertical: 4,
		borderRadius: 6,
		gap: 4,
	},
	occasionText: {
		fontSize: 11,
		fontWeight: "500",
		color: "#495057",
	},
	archivedLabel: {
		fontSize: 12,
		fontWeight: "400",
		fontStyle: "italic",
	},
	metadataGrid: {
		flexDirection: "row",
		flexWrap: "wrap",
		gap: 8,
		marginTop: 4,
	},
	metadataItem: {
		flexDirection: "row",
		alignItems: "center",
		backgroundColor: "#f8f9fa",
		paddingHorizontal: 8,
		paddingVertical: 4,
		borderRadius: 6,
		flex: 0,
		minWidth: "22%",
		maxWidth: "24%",
		gap: 4,
	},
	metadataValue: {
		fontSize: 11,
		color: "#495057",
		fontWeight: "500",
		flex: 1,
	},
	externalProductsContainer: {
		marginTop: 12,
		paddingTop: 12,
		borderTopWidth: 1,
		borderTopColor: "#e1e5e9",
	},
	neverOutBadge: {
		backgroundColor: "#c026d3",
		paddingHorizontal: 8,
		paddingVertical: 3,
		borderRadius: 12,
		alignSelf: "center",
	},
	neverOutText: {
		fontSize: 10,
		fontWeight: "600",
		color: "white",
		textTransform: "uppercase",
	},
	emptyExternalProducts: {
		padding: 16,
		alignItems: "center",
	},
	emptyText: {
		fontSize: 14,
		fontStyle: "italic",
		textAlign: "center",
	},
});
