#!/usr/bin/env bash
#
# upgrade-expo.sh — Upgrade this project's Expo SDK (and the matching devenv
# Android toolchain pins) in our devenv + bun setup.
#
# Context that makes this project specific:
#   * "Managed" Expo workflow — android/ and ios/ are gitignored and generated by
#     `expo prebuild`. The Android SDK/NDK/build-tools versions are therefore NOT
#     in the repo; they come from the installed Expo SDK and are mirrored by hand
#     into devenv.nix so local `expo run:android` builds find the right tools.
#   * bun is the package manager (driven by devenv languages.javascript.bun).
#   * The dev shell is provided by devenv; bun/expo only exist inside it.
#
# Two-track dependency model — do NOT use wildcard "*" ranges:
#   * Expo-governed deps (expo, expo-*, react, react-native, RN community libs,
#     @types/react, eslint-config-expo, @babel/core): let `expo install` pick the
#     SDK-compatible version. Never hand-edit these.
#   * Free tooling deps (eslint, typescript, @expo/ngrok, dom-to-image): caret
#     ranges bumped with `bun update`, BUT pin back any major the SDK toolchain
#     doesn't support yet. (Going 53->56 we had to pin back eslint 10 -> ^9,
#     typescript 6 -> ~5.9, @babel/core 8 -> ^7.x.)
#
# Usage:
#   scripts/upgrade-expo.sh <target-sdk-major>      # e.g. 56
#
# Run from the repo root. If you are not already inside the devenv shell, the
# script re-execs itself under `devenv shell`.

set -euo pipefail

TARGET="${1:-}"
if [[ -z "$TARGET" ]]; then
  echo "usage: scripts/upgrade-expo.sh <target-sdk-major>   (e.g. 56)" >&2
  exit 2
fi

# bun/expo live in the devenv shell — re-exec there if needed.
if ! command -v bun >/dev/null 2>&1; then
  echo "==> Not in devenv shell; re-executing under \`devenv shell\`..."
  exec devenv shell -- bash "$0" "$@"
fi

run() { echo; echo "==> $*"; "$@"; }

echo "==> Target Expo SDK major: $TARGET"

# 0. The eval must be healthy first. If a recent `devenv update` broke it with a
#    git-hooks assertion, run:
#       devenv inputs add git-hooks github:cachix/git-hooks.nix --follows nixpkgs
#    and confirm devenv.yaml still says `allowUnfree: true` (the inputs-add
#    command has rewritten it to the ignored `allow_unfree` before).

# 1. Single canonical lockfile = bun. Drop a stale yarn.lock if present.
[[ -f yarn.lock ]] && run rm -f yarn.lock

# 2. Bump Expo itself, then realign every Expo-governed dependency to the SDK.
run bunx --bun expo install "expo@^${TARGET}.0.0"
run bunx --bun expo install --fix

# 3. SDK-governed devDeps that --fix sometimes misses.
run bunx --bun expo install @types/react eslint-config-expo || true

# 4. Clean reinstall to dedupe native modules (kills duplicate-module warnings).
run rm -rf node_modules bun.lock
run bun install

# 5. Derive the devenv.nix Android pins straight from the installed native code.
NDK="$(sed -nE 's/^ndkVersion *= *"([^"]+)".*/\1/p' \
  node_modules/react-native/gradle/libs.versions.toml 2>/dev/null || true)"
COMPILE="$(sed -nE 's/.*safeExtGet\("compileSdkVersion", *([0-9]+)\).*/\1/p' \
  node_modules/expo-modules-core/android/ExpoModulesCorePlugin.gradle 2>/dev/null | head -1 || true)"
: "${NDK:=<check react-native/gradle/libs.versions.toml>}"
: "${COMPILE:=<check ExpoModulesCorePlugin.gradle>}"
echo
echo "==> Recommended devenv.nix android pins for SDK ${TARGET}:"
cat <<EOF
  android = {
    buildTools.version = ["${COMPILE}.0.0"];   # AGP default for compileSdk ${COMPILE}
    ndk.version        = ["${NDK}"];
    platforms.version  = ["${COMPILE}"];
  };
EOF
echo "    (Edit devenv.nix to match, then re-enter \`devenv shell\` to realize them.)"

# 6. expo-doctor is the authoritative compatibility check.
run bunx --bun expo-doctor || true

echo
echo "==> Manual follow-ups the SDK changelog / expo-doctor may require:"
cat <<'EOF'
  * Pin BACK any tooling major the SDK toolchain doesn't support yet
      (history: @babel/core must be ^7.x, eslint ^9, typescript ~5.9).
  * Install any new native peer deps flagged
      (e.g. reanimated 4 needs:  bunx expo install react-native-worklets).
  * Remove deps the SDK no longer allows
      (SDK 56 dropped direct @react-navigation/* alongside expo-router).
  * Fix app.json schema errors
      (SDK 56 removed `newArchEnabled` and android `edgeToEdgeEnabled`;
       add any config plugins it asks you to add to the plugins array).
  * Run `bun dev` once to regenerate typed-route types (.expo/types,
      expo-env.d.ts) before trusting `tsc --noEmit`.
EOF

echo
echo "==> Type-check & lint (report only — won't fail the script):"
run bunx --bun tsc --noEmit || true
run bunx --bun eslint . || true

echo
echo "==> Done. Review output, update devenv.nix, and smoke-test the app on device/emulator."
